import os

# ==============================================================================
# KINTSUGI SOVEREIGN RUNTIME - MEMORY SCHEMA FORGE
# ==============================================================================
# ARCHITECTURAL MANDATE: This bus is strictly bound to the x86-64 architecture. 
# Memory ordering across the C++/Python boundary relies on x86 Total Store Order 
# (TSO) for implicit release semantics on Python's unbarriered memory stores.
# ==============================================================================

CPP_HEADER = """// AUTO-GENERATED BY forge_schema.py - DO NOT EDIT MANUALLY
#pragma once
#include <atomic>
#include <cstdint>
#include <cstring>

constexpr uint32_t KINT_MAGIC = 0x4B494E54; // "KINT"
constexpr uint32_t BUS_VERSION = 2; // v2: SiliconGatePortal replaces KintsugiBus
constexpr size_t MAX_TEXT_PAYLOAD = 512;

// ------------------------------------------------------------------------
// THE SILICON GATE PORTAL
// ------------------------------------------------------------------------
// Software mirror of hardware bus-mastering (PROG_EN gate logic):
//   enable_programming_pin = 0 -> Core asleep (_mm_pause spin), HUD owns the bus
//   enable_programming_pin = 1 -> Core awake, seizes the AWE vault, HUD waits
//
// Protocol:
//   1. HUD writes text_payload, then stores pin = 1 (release)
//   2. Core spins on pin == 1 (acquire), wakes, runs prefill batch
//   3. Core writes token_id_payload with the result, then stores pin = 0 (release)
//   4. HUD's TriggerHardwareInterrupt() spin-wait sees pin == 0 (acquire), returns
// ------------------------------------------------------------------------
struct alignas(64) SiliconGatePortal {
    uint32_t magic;
    uint32_t version;

    // THE ENABLE PIN -- the atomic AND-gate equivalent
    alignas(64) std::atomic<int> enable_programming_pin;

    // THE DATA BUS -- the OR-gate payload
    alignas(64) uint32_t token_id_payload;
    char text_payload[MAX_TEXT_PAYLOAD];
};

constexpr size_t BUS_STRUCT_SIZE = sizeof(SiliconGatePortal);
"""

PYTHON_CTYPES = """# AUTO-GENERATED BY forge_schema.py - DO NOT EDIT MANUALLY
import ctypes

KINT_MAGIC = 0x4B494E54
BUS_VERSION = 2
MAX_TEXT_PAYLOAD = 512

class SiliconGatePortal(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ("magic", ctypes.c_uint32),               # offset 0
        ("version", ctypes.c_uint32),             # offset 4
        ("_pad0", ctypes.c_uint8 * 56),           # offset 8  -> pad to 64
        ("enable_programming_pin", ctypes.c_int32), # offset 64
        ("_pad1", ctypes.c_uint8 * 60),           # offset 68 -> pad to 128
        ("token_id_payload", ctypes.c_uint32),    # offset 128
        ("text_payload", ctypes.c_char * MAX_TEXT_PAYLOAD),  # offset 132
        ("_pad_tail", ctypes.c_uint8 * 60),       # offset 644 -> pad to 704
    ]

# Verified against actual g++ offsetof() output -- not hand-calculated:
#   magic=0, version=4, enable_programming_pin=64, token_id_payload=128, text_payload=132
#   C++ alignas(64) on the whole struct forces total size to round up to the
#   next 64-byte multiple: 132+512=644 -> rounds to 704. _pad_tail makes the
#   Python side match that exactly (644 without it, 704 with it).
#   sizeof = 704 bytes total, confirmed identical on both sides.

BUS_STRUCT_SIZE = ctypes.sizeof(SiliconGatePortal)
"""

def mint_files():
    print("[FORGE] Minting SSOT Schema (SiliconGatePortal v2)...")
    core_dir = "K:\\kintsugi\\core"
    if not os.path.exists(core_dir): os.makedirs(core_dir)
        
    cpp_path = os.path.join(core_dir, "shared_bus.h")
    py_path = os.path.join("K:\\kintsugi", "shared_bus.py")
    
    with open(cpp_path, "w", encoding="utf-8") as f: f.write(CPP_HEADER)
    print(f"[SUCCESS] Wrote C++ ABI -> {cpp_path}")
    
    with open(py_path, "w", encoding="utf-8") as f: f.write(PYTHON_CTYPES)
    print(f"[SUCCESS] Wrote Python ABI -> {py_path}")

if __name__ == "__main__":
    mint_files()