# AUTO-GENERATED BY forge_schema.py - DO NOT EDIT MANUALLY
import ctypes

KINT_MAGIC = 0x4B494E54
BUS_VERSION = 2
MAX_TEXT_PAYLOAD = 512

class SiliconGatePortal(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ("magic", ctypes.c_uint32),               # offset 0
        ("version", ctypes.c_uint32),             # offset 4
        ("_pad0", ctypes.c_uint8 * 56),           # offset 8  -> pad to 64
        ("enable_programming_pin", ctypes.c_int32), # offset 64
        ("_pad1", ctypes.c_uint8 * 60),           # offset 68 -> pad to 128
        ("token_id_payload", ctypes.c_uint32),    # offset 128
        ("text_payload", ctypes.c_char * MAX_TEXT_PAYLOAD),  # offset 132
        ("_pad_tail", ctypes.c_uint8 * 60),       # offset 644 -> pad to 704
    ]

# Verified against actual g++ offsetof() output -- not hand-calculated:
#   magic=0, version=4, enable_programming_pin=64, token_id_payload=128, text_payload=132
#   C++ alignas(64) on the whole struct forces total size to round up to the
#   next 64-byte multiple: 132+512=644 -> rounds to 704. _pad_tail makes the
#   Python side match that exactly (644 without it, 704 with it).
#   sizeof = 704 bytes total, confirmed identical on both sides.

BUS_STRUCT_SIZE = ctypes.sizeof(SiliconGatePortal)
