// AUTO-GENERATED BY forge_schema.py - DO NOT EDIT MANUALLY
#pragma once
#include <atomic>
#include <cstdint>
#include <cstring>

constexpr uint32_t KINT_MAGIC = 0x4B494E54; // "KINT"
constexpr uint32_t BUS_VERSION = 2; // v2: SiliconGatePortal replaces KintsugiBus
constexpr size_t MAX_TEXT_PAYLOAD = 512;

// ------------------------------------------------------------------------
// THE SILICON GATE PORTAL
// ------------------------------------------------------------------------
// Software mirror of hardware bus-mastering (PROG_EN gate logic):
//   enable_programming_pin = 0 -> Core asleep (_mm_pause spin), HUD owns the bus
//   enable_programming_pin = 1 -> Core awake, seizes the AWE vault, HUD waits
//
// Protocol:
//   1. HUD writes text_payload, then stores pin = 1 (release)
//   2. Core spins on pin == 1 (acquire), wakes, runs prefill batch
//   3. Core writes token_id_payload with the result, then stores pin = 0 (release)
//   4. HUD's TriggerHardwareInterrupt() spin-wait sees pin == 0 (acquire), returns
// ------------------------------------------------------------------------
struct alignas(64) SiliconGatePortal {
    uint32_t magic;
    uint32_t version;

    // THE ENABLE PIN -- the atomic AND-gate equivalent
    alignas(64) std::atomic<int> enable_programming_pin;

    // THE DATA BUS -- the OR-gate payload
    alignas(64) uint32_t token_id_payload;
    char text_payload[MAX_TEXT_PAYLOAD];
};

constexpr size_t BUS_STRUCT_SIZE = sizeof(SiliconGatePortal);
